version: 1
schema:
  type: struct
  fields:
  - name: INV_DATE_SK
    type: decimal(38,0)
    nullable: true
    metadata:
      description: ''
      mappings: []
      tags: []
  - name: INV_ITEM_SK
    type: decimal(38,0)
    nullable: true
    metadata:
      description: ''
      mappings: []
      tags: []
  - name: INV_WAREHOUSE_SK
    type: decimal(38,0)
    nullable: true
    metadata:
      description: ''
      mappings: []
      tags: []
  - name: INV_QUANTITY_ON_HAND
    type: decimal(38,0)
    nullable: true
    metadata:
      description: ''
      mappings: []
      tags: []
